language: java
install: mvn -X clean test install
sudo: true
deploy:
  provider: cloudfoundry 
  api: https://api.run.pivotal.io
  username: mac.sum@gmail.com
  password:"252295"
  organization: TOP GUNS
  space: development
